### ISSUE TITLE
Switching parameter crashes shiny app

### ISSUE THREAD

**Issue by mpartio** [harphub/harpVis#19]
Switching a parameter causes shiny app to crash (hang). Output in log is:

```
  no non-missing arguments to min; returning Inf
Warning: Error in data.frame: arguments imply differing number of rows: 0, 1
  76: stop
  75: data.frame
  72: observeEventHandler
   1: shiny::runApp
Warning in min(abs(leadtimes - 12)) :
  no non-missing arguments to min; returning Inf
Warning: Error in if: argument is of length zero
  72: observeEventHandler
   1: shiny::runApp

```

Happens on two different versions of Harp, one from 20200615 and one from 20200812. 

File [testdata.zip](https://github.com/harphub/harpVis/files/5160134/testdata.zip) contains two Harp result files that can both be loaded individually, but if first for example msl is loaded, and then parameter is changed to cctot this problem appears.

Is there a problem with the data or the UI?

**Comment by andrew-MET** [comment]
Please try updating to the latest version before reporting an issue.

**Comment by mpartio** [comment]
Seems to work with the latest version. Sorry for the noise.
